### PR TITLE
fix dynamic database variables with $_ENV

### PR DESCRIPTION
**Pull request by ewwink**
- remove script
- fix dynamic database variables with $_ENV
- update readme

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
Have just deployed this to my server, and it seems to be working. THANK YOU!

**Comment by dz0ny** [comment]
@ewwink Can you remove img.php, if users need specific operations after deploy they can use heroku release functionality or multipacks to have same result... Also squash commits please

**Comment by TheNotary** [comment]
In the latest commit, I have trouble pushing to a new instance, when the line `RUN rm vendor/piwik/piwik/config/config.ini.php` is run in the Dockerfile, it complains of no such file and halts the build process.  

Also, this PR hasn't gone anywhere for a while.  Maybe it should be amended by upstream?  https://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/

Then ewwink can merge against the result of upstream's interests and have sort of a dangling `adds image.php as alias` commit that that doesn't need to be shown in upstream's repo?

Thanks all for working on this, especially the 2.16.2 update =D

**Comment by dz0ny** [comment]
In favor of https://github.com/dz0ny/heroku-docker-piwik/pull/8

**Pull request closed without merging**
